version: '3.4'

services:
  financeapp:
    image: financeapp
    build:
      context: finance-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
